repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        exclude: "Jenkinsfile"
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.3.5
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/myint/docformatter
    rev: v1.3.1
    hooks:
      - id: docformatter
  - repo: local
    hooks:
      # run pylint in env since we need the dependencies
      - id: pylint
        name: pylint
        description: "pylint"
        entry: python
        language: system
        require_serial: true
        types: [python]
        pass_filenames: false
        verbose: true
        args:
          [-m, pylint, --exit-zero, --rcfile, .pylintrc, "workflow", "scripts"]
